import Head from "next/head";
import axios from "axios";
import Image from "next/image";
import { useEffect, useState } from "react";
import { BsSearch } from "react-icons/bs";
import Weather from "@/components/Weather";
import Spinner from "@/components/Spinner";

export default function Home() {
  const [city, setCity] = useState("Bengaluru");
  const [weather, SetWeather] = useState({});
  const [loading, setLoading] = useState(false);

  const fetchWeather = async (e) => {
    e.preventDefault();
    const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=imperial&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;
    // setLoading(true);
    try {
      const response = await new Promise((resolve, reject) => {
        axios.get(url).then(resolve).catch(reject);
      });
      console.log(response.data);
      SetWeather(response.data);
    } catch (err) {
      alert(err);
    }
    setCity("");
    setLoading(false);
  };

  return (
    <div>
      <Head>
        <title>Weather Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="absolute top-0 left-0 right-0 bottom-0 bg-black/35 z-[1]" />
      <Image
        src="https://images.unsplash.com/photo-1584267385494-9fdd9a71ad75?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
        layout="fill"
        alt="bg"
        className="object-cover "
      />

      <div className="pt-5 relative flex justify-between items-center max-w-[500px] w-full m-auto text-white z-10">
        <form
          onSubmit={(e) => fetchWeather(e)}
          className="flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 text-white rounded-xl">
          <div>
            <input
              onChange={(e) => setCity(e.target.value)}
              className="bg-transparent border-none text-white focus:outline-none text-2xl"
              type="text"
              placeholder="Search City"
            />
          </div>
          <button type="submit">
            {/* Ensure type attribute is set to "submit" */}
            <BsSearch size={20} />
          </button>
        </form>
      </div>
      {loading && <Spinner />}
      {weather.main && <Weather data={weather} />}
    </div>
  );
}
